// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: moodUi

#ifndef _MOODUI_UI_H
#define _MOODUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_options_png);   // assets/Options.png
LV_IMG_DECLARE( ui_img_comment_dots_png);   // assets/Comment Dots.png
LV_IMG_DECLARE( ui_img_1303973167);   // assets/Mode -  Dark.png
LV_IMG_DECLARE( ui_img_eye_png);   // assets/Eye.png
LV_IMG_DECLARE( ui_img_glow_png);   // assets/Glow.png
LV_IMG_DECLARE( ui_img_content_png);   // assets/Content.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
