// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: moodUi

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 150);
lv_obj_set_height( ui_Arc1, 150);
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arc1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_arc_set_bg_angles(ui_Arc1,270,269);
lv_obj_set_style_pad_left(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc1, 40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Arc1, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_options_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, -14 );
lv_obj_set_align( ui_Image3, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_comment_dots_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image4, 14 );
lv_obj_set_y( ui_Image4, 0 );
lv_obj_set_align( ui_Image4, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_1303973167);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image5, -14 );
lv_obj_set_y( ui_Image5, 0 );
lv_obj_set_align( ui_Image5, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image6, &ui_img_eye_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image6, 0 );
lv_obj_set_y( ui_Image6, 14 );
lv_obj_set_align( ui_Image6, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9, &ui_img_glow_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 222
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 216
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &ui_img_content_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 140
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
